board_1/config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo2 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo2/', include('pybo2.urls')),
]

board_1/pybo2/urls.py
from django.urls import path

from . import views

app_name = 'pybo2'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),

    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),

    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

board_1/pybo2/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

board_1/pybo2/forms.py
from django import forms
from pybo2.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }

        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

board_1/pybo2/views.py
from django.http import HttpResponse  # 삭제
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from django.contrib import messages


def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo2/question_list.html', context)



def detail(request, question_id):
    question =  get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo2/question_detail.html', context)




def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo2:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo2/question_detail.html', context)





def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo2:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo2/question_form.html', context)




# @login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # if request.user != question.author:
    #     messages.error(request, '수정권한이 없습니다')
    #     return redirect('pybo2:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo2:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo2/question_form.html', context)





# @login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # if request.user != question.author:
    #     messages.error(request, '삭제권한이 없습니다')
    #     return redirect('pybo2:detail', question_id=question.id)
    question.delete()
    return redirect('pybo2:index')






# @login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    # if request.user != answer.author:
    #     messages.error(request, '수정권한이 없습니다')
    #     return redirect('pybo2:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo2:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo2/answer_form.html', context)




# @login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    # if request.user != answer.author:
    #     messages.error(request, '삭제권한이 없습니다')
    # else:
    answer.delete()
    return redirect('pybo2:detail', question_id=answer.question.id)

board_1/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>

<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

board_1/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo2:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


board_1/templates/pybo2/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
{#        {% include "form_errors.html" %}#}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

board_1/templates/pybo2/question_detail.html
{#{% load static %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">#}
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <div class="container my-3">
        <!-- message 표시 -->
        {% if messages %}
            <div class="alert alert-danger my-3" role="alert">
                {% for message in messages %}
                    <strong>{{ message.tags }}</strong>
                    <ul>
                        <li>{{ message.message }}</li>
                    </ul>
                {% endfor %}
            </div>
        {% endif %}
        <!-- 질문 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2">

                        {{ question.create_date }}
                    </div>
                </div>

                <div class="my-3">
                    {#                {% if request.user == question.author %}#}
                    <a href="{% url 'pybo2:question_modify' question.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                       data-uri="{% url 'pybo2:question_delete' question.id %}">삭제</a>
                    {#                {% endif %}#}
                </div>
            </div>
        </div>
        <!-- 답변 -->
        <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
        {% for answer in question.answer_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>


                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                            <div class="badge bg-light text-dark p-2 text-start mx-3">
                                <div class="mb-2">modified at</div>
                                <div>{{ answer.modify_date }}</div>
                            </div>
                        {% endif %}
                        <div class="badge bg-light text-dark p-2">
                            {{ answer.create_date }}
                        </div>
                    </div>

                    <div class="my-3">
                        {#                {% if request.user == answer.author %}#}
                        <a href="{% url 'pybo2:answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'pybo2:answer_delete' answer.id %}">삭제</a>
                        {#                {% endif %}#}
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- 답변 등록 -->
        <form action="{% url 'pybo2:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <div>
                                <strong>{{ field.label }}</strong>
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea name="content" id="content" class="form-control" rows="10"></textarea>
            </div>
            <input type="submit" value="답변등록" class="btn btn-primary">
        </form>
    </div>
{% endblock %}


{% block script %}
    <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function (element) {
            element.addEventListener('click', function () {
                if (confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                }
                ;
            });
        });
    </script>
{% endblock %}

board_1/templates/pybo2/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

board_1/templates/pybo2/question_list.html
{#{% load static %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">#}
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo2:detail' question.id %}">{{ question.subject }}</a>
                 {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo2:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}